### ISSUE TITLE
Floated tables

### ISSUE THREAD

**Issue by digicommsucl** [UCL-WAMS/indigo#106]
Tables are, by default, floated left:

https://github.com/UCL-WAMS/indigo/blob/master/sass/base/_tables.scss#L6

This is causing problems in Firefox (Chrome seems fine) - e.g. 
<img width="975" alt="screen shot 2015-08-03 at 08 59 57" src="https://cloud.githubusercontent.com/assets/2742949/9033339/161de684-39be-11e5-873e-e921b25a86e1.png">

I'm sure I'm missing something obvious, but why are tables set to float like this?

**Comment by aaronBeryUcl** [comment]
@digicommsucl  we have looked at this and we believe it will be safe to remove the float on tables so we will implement this shortly
