### ISSUE TITLE
replace global-masthead off-canvas 'close' button

### ISSUE THREAD

**Issue by sturobson** [UCL-WAMS/indigo#4]
So, for the search results I was thinking of spriting the 2 social icons required (at least for oldIE as I might data-uri for new browsers as they'll be tiny).

In doing this and looking through existing code I noticed that the off-canvas close for the global-masthead is a separate call for an image. 
Firstly, I'd suggest not having an image in the HTML for this as it's not really 'content' and moving it to a background-image (hence adding it to the sprite).
On reflection of this, for the off-canvas for facets I'm using CSS to create the same result.

So... to move forward shall we 

a) move the image to a background-image and add to a UCL spritesheet 

or 

b) remove it and make the circle with CSS (this would be a square in <IE8)

Thoughts?

**Comment by aaronBeryUcl** [comment]
closing this and WAMS will implement
