### ISSUE TITLE
Modifications to typeahead lib make it awkward to reuse

### ISSUE THREAD

**Issue by helenst** [UCL-WAMS/indigo#95]
There seem to be some local modifications to Indigo's version of typeahead.bundle.js which make it specific to the Search dropdown (e.g. it replaces position: absolute with position:fixed) - it changes the styles which are applied globally to anything else that tries to use typeahead.

I'm trying to provide typeahead functionality in a form I am creating on an Indigo site. It seems the options are either to load my own unmodified copy of typeahead (not ideal to have two), or add enough styles to override the Search modifications. It would be nice if the library could be provided unmodified, with default styles overridden for Search through stylesheets (presumably this would also make it easier to upgrade to future versions of the library)

**Comment by joelsmithucl** [comment]
Hi Helen 

Thanks for the feedback - and quite agree it would be best if the file was unmodified and so we'll definitely look into it. If you have any further details which could give us a head start please do send them over.

Out of interest what indigo site are you building the form for?

Many thanks 

Joel

**Comment by helenst** [comment]
Hi Joel

Thanks for the reply. It's for Dashboard, which is a project currently under development for cataloguing research software.

Helen

**Comment by helenst** [comment]
Hi Joel

Just realised I didn't answer your request for further details. If you have a look here:

https://github.com/UCL-WAMS/indigo/blob/master/js/src/typeahead.bundle.js#L684

you'll see some of the local modifications I'm talking about

Diffing it against the equivalent standard version of the typeahead lib:

https://www.diffchecker.com/6u93z93y

(that's https://raw.githubusercontent.com/UCL-WAMS/indigo/master/js/src/typeahead.bundle.js vs
https://raw.githubusercontent.com/twitter/typeahead.js/v0.10.2/dist/typeahead.bundle.js)

Helen

**Comment by joelsmithucl** [comment]
Thanks Helen that's really helpful.

Joel

**Comment by aaronBeryUcl** [comment]
- Funnelback, our search application partner built our global search and the autocomplete uses the typeahead script.
- We have then ported their autocomplete code into Indigo.
- Helen has pointed out that the library file has been modified from twitters original version.

I would propose we update the notes at the top of the current file to clearly state the file has been modified for UCL

We can then include an untouched version and name it twitter.typeahead.js so Helen is able to use the original library.

What we cannot do though, is modify the current typeahead as there may be applications we are not aware of using it.

@joelsmithucl  how does this sound?
