### ISSUE TITLE
Missing icon images

### ISSUE THREAD

**Issue by helenst** [UCL-WAMS/indigo#98]
Sass files (e.g. patterns/_message.scss) refer to icons which do not appear to be included in the repository, e.g. alert.png and success.png so result in 404 errors when these patterns are used.

**Comment by aaronBeryUcl** [comment]
Hi Helen,

We have reviewed this and released a patch for the missing icons.

This can be seen on the form.html page at the root of the repo

Best
Aaron

**Comment by helenst** [comment]
Thanks!
